### PR TITLE
Refactor CLI

### PR DESCRIPTION
**Pull request by shu8**
This PR refactors the XRPackage CLI to make it more readable, testable, and maintainable.

- Each command is now in it's own module/file in the `commands/` directory, following the yargs ['command module' format](https://github.com/yargs/yargs/blob/master/docs/advanced.md#providing-a-command-module).
- Utility functions used by more than 1 command are now in the `utils.js` file
- Constants shared between the various files to `constants.js`
- I've modified some of the commands slightly to make them a bit more readable, e.g. https://github.com/MLH-Fellowship/xrpackage-cli/pull/5/commits/0c6800a8458de708ac59adc47b43d30a33d19959
- Used more of `yargs`' built-in features, e.g. using the `default` property so we don't manually set a default value for arguments
- Reduced nesting of `ifs` where possible by returning early
- Removed stale/unsupported code

Side note: it might be easier to add some 'unit' testing into the CLI now, if we want -- we could use https://github.com/yargs/yargs/blob/master/docs/advanced.md#testing-a-command-module as a starter.

**Note:** I branched off of https://github.com/webaverse/xrpackage-cli/pull/19 to for this PR, so that one would need reviewing/merging and then rebasing this branch off master first :)

### CODE REVIEW

**Comment by avaer** [comment]
#19 was merged.

**Comment by avaer** [comment]
This looks great, and a good platform to base unit testing off of.  Opened an issue for it here: https://github.com/webaverse/xrpackage-cli/issues/22

If we are going to start testing, however, I feel like there is more of a benefit to starting with the core XRPackage runtime -- that code is more complicated and more critical to everything working than the CLI, and it also has no tests 😅 .

**Comment by shu8** [comment]
Thanks @avaer, I've rebased

**Comment by shu8** [comment]
Also, yeah I think XRPackage testing would be more beneficial, although I'm not really sure how to get started with that as it's less 'unit' testing than overall testing?

**Comment by avaer** [comment]
I think it would still be unit testing; there are well defined categories of things we should test. For example:

- Parsing all of the package types
- Handling bad data
- Adding/removing packages from the scene
- Getting screenshots loaded
- Getting collision meshes
- "Wearing" packages as avatars
- Download/upload packages programmatically
- Race conditions/stress testing (I expect there would be legitimate bugs discovered here)
- Rough performance tests

**Comment by avaer** [comment]
I expanded on the unit testing of XRPackage in that repo: https://github.com/webaverse/xrpackage/issues/64

**Pull request merged**
